import React from 'react';
import GameProviders from './GameProviders';

const GameProvidersContainer = props => {

    return (
        <ul className="slider-content game-providers-content mb-3">
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/evolution.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/evolution"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/asiagaming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/asiagaming"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/pragmatic.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/pragmatic"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/gameart.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/gameart"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/betsoft.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=182"}
                href={"https://sportsbet.io/casino/providers/betsoft"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/booming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/booming"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/playngo.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/playngo"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/endorphina.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/endorphina"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/microgaming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/microgaming"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/microgaming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/yggdrasil"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/tgc.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/tgc"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/booongo.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/booongo"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/lotusgaming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/lotusgaming"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/blueprint.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/blueprint"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/spinmatic.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/spinmatic"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/superspadeclub.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=182"}
                href={"https://sportsbet.io/casino/providers/superspadeclub"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/kalambagames.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=182"}
                href={"https://sportsbet.io/casino/providers/kalambagames"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/tomhorn.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/tomhorn"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/caleta.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/caleta"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/indi-slots.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=116"}
                href={"https://sportsbet.io/casino/providers/indi-slots"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/onetouch.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/onetouch"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/tangente.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/tangente"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/wazdan.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/wazdan"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/ganapati.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/ganapati"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/gamatron.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/gamatron"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/spadegaming.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/spadegaming"}>
            </GameProviders>
            <GameProviders
                image={"https://heathmont.imgix.net/bitcasino/images/providers/ebet.png?auto=compress%2Cformat&ixlib=react-9.0.1&w=100"}
                href={"https://sportsbet.io/casino/providers/ebet"}>
            </GameProviders>
        </ul>
    )
}
export default GameProvidersContainer